services:
  rabittmq:
    image: rabbitmq:management
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - crackhash
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGODB_USER: user
      MONGODB_DATABASE: worker
      MONGODB_PASS: userpassword
      MONGO_INITDB_DATABASE: worker
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db
networks:
  crackhash:
    driver: bridge
volumes:
  mongodb_data_container: