services:
  manager:
    image: crackhash-manager:latest
    restart: unless-stopped
    hostname: "manager"
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
    networks:
      - crackhash
    environment:
      WORKER_ADDRESS_0: http://crackhash-worker-1:8081
      WORKER_ADDRESS_1: http://crackhash-worker-2:8081
      WORKER_ADDRESS_2: http://crackhash-worker-3:8081
      WORKER_ADDRESS_3: http://crackhash-worker-4:8081
      WORKER_ADDRESS_4: http://crackhash-worker-5:8081
      WORKER_ADDRESS_5: http://crackhash-worker-6:8081
      WORKER_ADDRESS_6: http://crackhash-worker-7:8081
      WORKER_ADDRESS_7: http://crackhash-worker-8:8081
  worker:
    image: crackhash-worker:latest
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - crackhash
    environment:
      MANAGER_ADDRESS: http://crackhash-manager-1:8080
      BPL_JVM_THREAD_COUNT: 50
      BPL_JVM_HEAP_SIZE: 200M
      BPL_JVM_CALCULATE_HEAP: false
      JAVA_TOOL_OPTIONS: "-Xmx250M -Xms100M -XX:MaxMetaspaceSize=64M -XX:ReservedCodeCacheSize=64M -XX:MaxDirectMemorySize=8M"
    deploy:
      replicas: 8

networks:
  crackhash:
    driver: bridge