server:
  port: 8081

manager:
  address: ${MANAGER_ADDRESS}
heartbeat:
  sendRate: 5000
spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: user
    password: password
    virtual-host: /
