server:
  port: 8080
heartbeat:
  clearRate: 5000
  timeout: 10000
spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:user}
    password: ${RABBITMQ_PASSWORD:password}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:/}
  data:
    mongodb:
      uri: ${MONGODB_URL:mongodb://root:rootpassword@mongodb:27017/worker?authSource=admin}
